config/routes.rb
Rails.application.routes.draw do

  resources :news
  devise_for :users
  get 'home/index'
  root 'home#index'
resources :orders
resources :customers
resources :payments
resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  STREETS = ["London Plain ", "Wax Myrtle ", "Mint "]
  has_many :orders, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :payments, dependent: :destroy

  validates :fam_name, presence: true, length: { minimum: 3 }
  validates :fam_name, uniqueness: true
  validates :st_name, presence: true
  validates :st_numb, presence: true
  # validates :st_numb, uniqueness: true
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10}
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

def full_address
    "#{st_numb} #{st_name} ct, Cary, NC, 27513"
end



end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  # layout 'customer_layout'
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
      if @customer.save
        flash.notice = "The customer record was  successfully created."
        redirect_to @customer
      else
        flash.now.alert = @customer.errors.full_messages.to_sentence
        render :new
      end
    end


  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    if @customer.update(customer_params)
      flash.notice = "The customer record was updated successfully."
      redirect_to @customer
    else
      flash.now.alert = @customer.errors.full_messages.to_sentence
      render :edit
    end
    end

  #
  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:fam_name, :st_numb, :st_name, :phone, :email)
    end
    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to customers_path
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h6>Please complete the information below to create your Evergreen Resident Account.  One account per property address:</h6>

  <div class="field">
    <%= f.label :family_name %>
    <%= f.text_field :fam_name %>
  </div>
  <div class="field">
    <%= f.label :phone_Number %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Street_number %>
    <%= f.text_field :st_numb %>
  </div>


  <div class="field">
    <%= f.label :st_name %><br>
    <% Customer::STREETS.each do |s| %>
      <%= f.radio_button :st_name, s %>
      <%= f.label :st_name, s, value: s, class: "checkbox-label" %><br>
    <% end %>
  </div>


  <div class="actions">
<%= f.submit value: @submit_text, "data-disable-with" => @submit_text, class: "btn btn-info btn-sm text-white" %>
  </div>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer, :class => "btn btn-info btn-sm text-white" %>

<%= link_to 'Back', customers_path, :class => "btn btn-info btn-sm text-white" %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h5>Neighbors Contact information Ordered by Family Last Name:</h5>


<table class="table table-striped"  >
  <thead>
    <tr>
      <th>Family Name</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Address</th>

      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fam_name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.full_address %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighbor', new_customer_path, :class => "btn btn-info btn-sm text-white" %> <%= link_to 'Home', home_index_path, :class => "btn btn-info btn-sm text-white" %>

app/views/customers/new.html.erb
<h1>New Neighbor</h1>

<%= render 'form', customer: @customer %>



<%= link_to 'Back to List', customers_path, :class => "btn btn-info btn-sm text-white" %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Family Name:</strong>
  <%= @customer.fam_name %>
</p>

<p>
  <strong>Street Number:</strong>
  <%= @customer.st_numb %>
</p>

<p>
  <strong>Street Name:</strong>
  <%= @customer.st_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer), :class => "btn btn-info btn-sm text-white" %>
<%= link_to 'Back to List', customers_path, :class => "btn btn-info btn-sm text-white" %>



<div id="orders">
  <% if @customer.orders.present? %>
    <h3>Customer Orders:</h3>
  <% end %>
  <% @customer.orders.each do |order| %>
  <table>
    <thead>
      <tr>
        <th>Document Name</th>

        <th>Qty </th>

        <th>Description </th>

        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
          <tr>
          <td><%= order.doc_name %></td>
          <td><%= order.doc_count %></td>
          <td><%= order.description %></td>

          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>