config/routes.rb
Rails.application.routes.draw do

  resources :news
  devise_for :users
  get 'home/index'
  root 'home#index'
resources :orders
resources :customers
resources :payments
resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
  validates :sqft, presence: true
  validates :sqft, numericality: { greater_than_or_equal_to: 1}
  validates :customer_id, presence: true
  validates_presence_of :customer
  validates :pay_freq, inclusion: { in: [true, false] }



def mult
  fee = 0.15 * sqft.to_i
end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:pay_freq, :customer_id, :sqft)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(payment) do |p| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_customer">
  <%= p.label :Neighbor_Name%>
   <div class="customers">
  <%= p.collection_select :customer_id, Customer.all,:id, :fam_name, include_blank: true%>
  </div>
 </div>
  <div class="field">
    <%= p.check_box :pay_freq %>
    <%= p.label :Annual_Payment, class: "checkbox-label" %><br>
  </div>


  <h4>Please enter your house square footage below to calculate your Annual Fee:</h4>


  <div class="field">
      <%= p.label :sqft %>
      <%= p.number_field :sqft %>
  </div>

<div class="actions">
<%= p.submit value: @submit_text, "data-disable-with" => @submit_text, class: "btn btn-info btn-sm text-white" %>
</div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', payment_path, :class => "btn btn-info btn-sm text-white" %> 
<%= link_to 'Back', payments_path, :class => "btn btn-info btn-sm text-white" %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Payment Sheet ordered by Neighbor's Family Name:</h3>

<table class="table table-striped " >
  <thead>
    <tr>

      <th>Family Name</th>
      <th>Sqft</th>
      <th>Annual Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>

        <td><%= payment.customer.fam_name%></td>
        <td><%= payment.sqft%></td>
        <td><%= payment.mult%></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Delete', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Calculate Fee', new_payment_path, :class => "btn btn-info btn-sm text-white" %> <%= link_to 'Home', home_index_path, :class => "btn btn-info btn-sm text-white" %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path, :class => "btn btn-info btn-sm text-white"%>

app/views/payments/show.html.erb
<h4>The Annual HOA fee for your Household is:   <strong><%= @payment.mult %> dollars. </strong></h4>

<h4>Your due date is <strong>January 30th, 2021.</strong></h4>

<h4>Please contact us if you have any further questions.</h4>




<%= link_to 'Edit', edit_payment_path, :class => "btn btn-info btn-sm text-white" %>
<%= link_to 'Back', payments_path, :class => "btn btn-info btn-sm text-white" %>