config/routes.rb
Rails.application.routes.draw do

  resources :news
  devise_for :users
  get 'home/index'
  root 'home#index'
resources :orders
resources :customers
resources :payments
resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  validates :title, presence: true
  validates :body, presence: true
  validates :customer_id, presence: true
  validates_presence_of :customer
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)


    # respond_to do |format|
      if @post.save
        flash.notice = "Your post  was  successfully placed."
        redirect_to @post
      else
        flash.now.alert = @post.errors.full_messages.to_sentence
        render :new
      end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :customer_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field_customer">
    <%= form.label :Family_Name %>
    <div class="customers">
      <%= form.collection_select :customer_id, Customer.all, :id, :fam_name, include_blank: true %>
    </div>
  </div>


  <br>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>



<br>
<br>

  <div class="actions">
      <%= form.submit value: @submit_text, "data-disable-with" => @submit_text, class: "btn btn-info btn-sm text-white" %>
    </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, :class => "btn btn-info btn-sm text-white" %>
<%= link_to 'Back', posts_path, :class => "btn btn-info btn-sm text-white" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<img class="mb-4  rounded img-fluid  max-width: 100% height: auto " <%= image_tag("jumbobanner.jpeg", border: 0) %>


<h2> News and Events: </h2>

<tbody>
<% @posts.each do |post| %>
  <div class="container pt-2">

    <h4 class="mb-2 ">Post Title: <%= post.title %></h4>
    <h4 class="mb-2 text-muted"><%= post.body %></h4>
    <h4 class="mb-2 ">Family Name: <%= post.customer.fam_name %></h4>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <br>
    <br>
</div>

<% end %>
</tbody>


<br>
<%= link_to 'New Post', new_post_path, :class => "btn btn-info btn-sm text-white" %> <%= link_to 'Home', home_index_path, :class => "btn btn-info btn-sm text-white"  %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, :class => "btn btn-info btn-sm text-white" %>

app/views/posts/show.html.erb
<p>
  <strong>News Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>News:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @post.customer.fam_name%>
</p>


<%= link_to 'Edit', edit_post_path, :class => "btn btn-info btn-sm text-white"  %> 
<%= link_to 'Back', posts_path, :class => "btn btn-info btn-sm text-white" %>