config/routes.rb
Rails.application.routes.draw do

  resources :news
  devise_for :users
  get 'home/index'
  root 'home#index'
resources :orders
resources :customers
resources :payments
resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">

  <div class="container">
     <a class="navbar-brand order-1 mr-0" href="https://www.codethedream.org" target="_blank"> Presented by Code the Dream</a> 



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%# <a class="nav-item nav-link " href="#home">Home <span class="sr-only">(current)</span></a> %>

        <%# <a class="nav-item nav-link" href="#about">About</a> %>

         <li class='nav-item'><%= link_to 'Home', home_index_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Neighbors', customers_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Orders', orders_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'News and Events', posts_path, class: 'nav-link' %></li>
        <%=link_to 'News', news_index_path %>
        <li class='nav-item'><%= link_to 'Annual Fees', payments_path, class: 'nav-link' %></li>

        <% if current_user %>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to 'Sign up', new_user_registration_path %>
<%= link_to 'Sign in', new_user_session_path %>
<%end%>
    </div>
  </div>
</nav>

    <!--    navbar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= content_for?(:title) ? yield(:title) : "Evergreen Hoa Website" %></title>
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Evergreen" %>">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= content_for?(:content) ? yield(:content) : yield %>

    </main>

  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evergreen HOA Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/layouts/customers.html.erb
<% content_for :content do %>
  <div class="jumbotron bg-info text-white text-sm-center pt-5">
    <h1 class= "mt-5">Neighbors Info</h1>

  </div>



  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p>
          <%= yield %>
        </p>
      </div>
      <div class="col-lg-6">

      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/evergreen.html.erb
<% content_for :content do %>
  <div class="jumbotron text-center">
    <h1>Evergreen HOA Info</h1>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p><%= yield %></p>
      </div>
      <div class="col-lg-6">
        <p>
          <div class="caption">Welcome to our Community!</div>
          <%= image_tag("Test Evergreen pic.jpeg", border: 0) %>

        </p>
      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/order_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evergreen HOA Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !flash[:alert].nil? %>
      <p class="my_alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/orders.html.erb
<% content_for :content do %>

    <div class="jumbotron jumbotron bg-info text-white text-sm-center pt-5 ">
     <h1 class= "mt-5">Documents/Permits Orders</h1>
    </div>


  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p>
          <%= yield %>
        </p>
      </div>
      <div class="col-lg-6">

      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/payments.html.erb
<% content_for :content do %>
<div class="jumbotron jumbotron bg-info text-white text-sm-center pt-5 ">
 <h1 class= "mt-5">Annual Fees Info</h1>
</div>


  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p>
          <%= yield %>
        </p>
      </div>
      <div class="col-lg-6">

      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/posts.html.erb
<% content_for :content do %>
  

  <div class="jumbotron jumbotron bg-info text-white text-sm-center pt-5 ">
   <h1 class= "mt-5">Neighbors Forum</h1>
  </div>


  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <p>
          <%= yield %>
        </p>
      </div>
      <div class="col-lg-6">

      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>